question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you can take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you die in the House of Parliament, you get a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can kill a small dog.", "answer": "True"},
    {"text": "The Great Wall of China is visible from space.", "answer": "False"},
    {"text": "Bananas grow on trees.", "answer": "False"},
    {"text": "Sharks are mammals.", "answer": "False"},
    {"text": "The human body has four lungs.", "answer": "False"},
    {"text": "Goldfish have a memory span of several months.", "answer": "True"},
    {"text": "Lightning never strikes in the same place twice.", "answer": "False"},
    {"text": "The Eiffel Tower can grow taller during summer.", "answer": "True"},
    {"text": "Mount Everest is the tallest mountain in the world.", "answer": "True"},
    {"text": "Water boils at 100 degrees Celsius at sea level.", "answer": "True"},
    {"text": "The Pacific Ocean is the largest ocean on Earth.", "answer": "True"},
    {"text": "An ostrich’s eye is bigger than its brain.", "answer": "True"},
    {"text": "Bats are blind.", "answer": "False"},
    {"text": "The Great Pyramid of Giza was built by aliens.", "answer": "False"},
    {"text": "There are more stars in the universe than grains of sand on Earth.", "answer": "True"},
    {"text": "Venus is the closest planet to the Sun.", "answer": "False"},
    {"text": "Octopuses have three hearts.", "answer": "True"},
    {"text": "Penguins can fly.", "answer": "False"},
    {"text": "The human brain is mostly water.", "answer": "True"},
    {"text": "Humans and dinosaurs lived at the same time.", "answer": "False"},
    {"text": "Honey never spoils.", "answer": "True"},
    {"text": "The Amazon rainforest produces 20% of the world’s oxygen.", "answer": "True"},
    {"text": "Sound travels faster in air than in water.", "answer": "False"},
    {"text": "There are seven continents on Earth.", "answer": "True"},
    {"text": "Sloths can hold their breath longer than dolphins.", "answer": "True"}
]
